
database: &database
  rails_demo_db:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    host: localhost
    database: rails-demo-db
    pool: 5
    username: root
    password: 123456
    port: 3306

production:
  <<: *database

development:
  <<: *database
  <<: *database

test:
  rails_demo_db:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: rails_demo_test
    pool: 5
    username: root
    password: 123456
    host: 127.0.0.1
    port: 3306
